name: build-docker-container
on: [push]
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
